- type: entity
  abstract: true
  parent: Clothing
  id: CEClothingEyesBase
  categories: [ ForkFiltered ]
  components:
  - type: Sprite
    state: icon
  - type: Item
    size: Small
    shape:
    - 0, 0, 0, 0
  - type: Clothing
    equipDelay: 0.4
    unequipDelay: 0
    slots: [eyes]

- type: entity
  abstract: true
  parent: CEClothingEyesBase
  id: CEClothingEyesGogglesFoldableBase
  categories: [ ForkFiltered ]
  components:
  - type: Foldable
    canFoldInsideContainer: true
    unfoldVerbText: ce-fold-pull-from-head-verb
    foldVerbText: ce-fold-pull-on-head-verb
  - type: FoldableClothing
    foldedEquippedPrefix: flipped
    foldedHeldPrefix: flipped