- type: entity
  abstract: true
  parent: Clothing
  id: CEClothingMaskBase
  categories: [ ForkFiltered ]
  components:
  - type: Sprite
    state: icon
  - type: Item
    size: Normal
  - type: Clothing
    equipDelay: 0.7
    unequipDelay: 0.4
    slots: [mask]

- type: entity
  abstract: true
  parent: CEClothingMaskBase
  id: CEClothingMaskIdentityBlockerBase
  categories: [ ForkFiltered ]
  components:
  - type: IdentityBlocker
  - type: IngestionBlocker