- type: entity
  id: CEDrinkBottleBase
  abstract: true
  parent:
  - DrinkBase
  - DrinkBaseOpenable
  categories: [ ForkFiltered ]
  components:
  - type: Openable
    sound:
      collection: bottleOpenSounds
    closeable: true
    closeSound:
      collection: bottleCloseSounds
  - type: Appearance
  - type: GenericVisualizer
    visuals:
      enum.OpenableVisuals.Opened:
        enum.OpenableVisuals.Layer:
          True: {visible: false} # lid off
          False: {visible: true} # lid on
  - type: Sprite
    noRot: true
    layers:
    - state: fill-1
      map: ["enum.SolutionContainerLayers.Fill"]
      visible: false
    - state: icon
    - state: stopper
      map: ["enum.OpenableVisuals.Layer"]
  - type: ExaminableSolution
    solution: drink
    examinableWhileClosed: true
    heldOnly: false
  - type: SolutionContainerVisuals
    solutionName: drink
    maxFillLevels: 6
    fillBaseName: fill-
    #inHandsMaxFillLevels: 3 #TODO: draw inhands
    #inHandsFillBaseName: -fill-
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: FlimsyGlass
  - type: Destructible
    thresholds:
    - trigger: # Overkill threshold
        !type:DamageTrigger
        damage: 200
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
    - trigger:
        !type:DamageTrigger
        damage: 5
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: GlassBreak
      - !type:SpillBehavior { }
      - !type:SpawnEntitiesBehavior
        spawn:
          CEGlassShard:
            min: 1
            max: 1
        transferForensics: true
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: DamageOnLand
    ignoreResistances: true
    damage:
      types:
        Blunt: 5 # so fragile it smashes when thrown
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 5
#  - type: EmitSoundOnLand TODO other materials need a sound
#    sound:
#      collection: GlassCrack
  - type: PhysicalComposition
    materialComposition:
      CEGlass: 10