- type: entity
  abstract: true
  parent: BaseObjective
  id: CEBaseAmbitionObjective
  components:
  - type: Objective
    difficulty: 0
    issuer: ce-objective-issuer-ambition
    icon:
      sprite: _CE/Objects/Materials/leather.rsi # TODO Better icon
      state: rugged_leather
  - type: CEAmbitionObjective
