- type: tile
  editorHidden: false
  id: CEStone
  name: ce-tiles-base
  sprite: /Textures/_CE/Tiles/cave.png
  variants: 14
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  baseTurf: Space
  deconstructTools: [ CEPickaxe ]
  itemDrop: CEStoneBlock1
  isSubfloor: true
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  indestructible: true
