- type: entity
  abstract: true
  parent: Clothing
  id: CEClothingGlovesBase
  categories: [ ForkFiltered ]
  components:
  - type: Clothing
    equipDelay: 0.2
    unequipDelay: 0.2
    slots:
    - gloves
  - type: Sprite
    state: icon
  - type: Item
    size: Normal
    storedRotation: -90

